lernparadies_lernparadies_home:
    pattern:  /
    defaults: { _controller: LernparadiesLernparadiesBundle:Default:index }

lernparadies_lernparadies_benutzergruppe:
    resource: "@LernparadiesLernparadiesBundle/Resources/config/routing/benutzergruppe.yml"
    prefix:   /benutzergruppe

lernparadies_lernparadies_benutzer:
    resource: "@LernparadiesLernparadiesBundle/Resources/config/routing/benutzer.yml"
    prefix:   /benutzer