lernparadies_lernparadies_home:
    pattern:  /
    defaults: { _controller: LernparadiesLernparadiesBundle:Default:index }
LernparadiesLernparadiesBundle_sprache:
    resource: "@LernparadiesLernparadiesBundle/Resources/config/routing/sprache.yml"
    prefix:   /sprache