lernparadies_lernparadies_home:
    pattern:  /
    defaults: { _controller: LernparadiesLernparadiesBundle:Default:index }
lernparadies_lernparadies_benutzergruppe:
    resource: "@LernparadiesLernparadiesBundle/Resources/config/routing/benutzergruppe.yml"
    prefix:   /benutzergruppe
lernparadies_lernparadies_benutzer:
    resource: "@LernparadiesLernparadiesBundle/Resources/config/routing/benutzer.yml"
    prefix:   /benutzer
LernparadiesLernparadiesBundle_sprache:
    resource: "@LernparadiesLernparadiesBundle/Resources/config/routing/sprache.yml"
    prefix:   /sprache

login:
    pattern:   /login
    defaults:  { _controller: LernparadiesLernparadiesBundle:Default:login }
login_check:
    pattern:   /login_check
# Definiert wird das logout-System im security.yml
logout:
    pattern:   /logout

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
_sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password