lernparadies_lernparadies_home:
    pattern:  /
    defaults: { _controller: LernparadiesLernparadiesBundle:Default:index }
lernparadies_lernparadies_benutzergruppe:
    resource: "@LernparadiesLernparadiesBundle/Resources/config/routing/benutzergruppe.yml"
    prefix:   /benutzergruppe
lernparadies_lernparadies_benutzer:
    resource: "@LernparadiesLernparadiesBundle/Resources/config/routing/benutzer.yml"
    prefix:   /benutzer
LernparadiesLernparadiesBundle_sprache:
    resource: "@LernparadiesLernparadiesBundle/Resources/config/routing/sprache.yml"
    prefix:   /sprache
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin