lernparadies_lernparadies_start:
    pattern:  /
    defaults: { _controller: LernparadiesLernparadiesBundle:Default:index }

LernparadiesLernparadiesBundle_benutzergruppe:
        resource: "@LernparadiesLernparadiesBundle/Resources/config/routing/benutzergruppe.yml"
        prefix:   /benutzergruppe

LernparadiesLernparadiesBundle_benutzer:
        resource: "@LernparadiesLernparadiesBundle/Resources/config/routing/benutzer.yml"
        prefix:   /benutzer
