parameters:
#    lernparadies_lernparadies.example.class: Lernparadies\LernparadiesBundle\Example

services:
    lernparadies.lernparadiest.admin.sprache:
        class: Lernparadies\LernparadiesBundle\Admin\SpracheAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Lernparadies-Basis, label: Sprachen }
        arguments: [null, Lernparadies\LernparadiesBundle\Entity\Sprache, LernparadiesLernparadiesBundle:SpracheAdmin]