parameters:
#    lernparadies_lernparadies.example.class: Lernparadies\LernparadiesBundle\Example

services:
#    lernparadies_lernparadies.example:
#        class: %lernparadies_lernparadies.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
