benutzergruppe:
    pattern:  /
    defaults: { _controller: "LernparadiesLernparadiesBundle:Benutzergruppe:index" }

benutzergruppe_show:
    pattern:  /{id}/show
    defaults: { _controller: "LernparadiesLernparadiesBundle:Benutzergruppe:show" }

benutzergruppe_new:
    pattern:  /new
    defaults: { _controller: "LernparadiesLernparadiesBundle:Benutzergruppe:new" }

benutzergruppe_create:
    pattern:  /create
    defaults: { _controller: "LernparadiesLernparadiesBundle:Benutzergruppe:create" }
    requirements: { _method: post }

benutzergruppe_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "LernparadiesLernparadiesBundle:Benutzergruppe:edit" }

benutzergruppe_update:
    pattern:  /{id}/update
    defaults: { _controller: "LernparadiesLernparadiesBundle:Benutzergruppe:update" }
    requirements: { _method: post|put }

benutzergruppe_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "LernparadiesLernparadiesBundle:Benutzergruppe:delete" }
    requirements: { _method: post|delete }
