parameters:
#    lernparadies_vokali.example.class: Lernparadies\VokaliBundle\Example

services:
#    lernparadies_vokali.example:
#        class: %lernparadies_vokali.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
