parameters:
#    lernparadies_vokali.example.class: Lernparadies\VokaliBundle\Example

services:
#    lernparadies_vokali.example:
#        class: %lernparadies_vokali.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
services:
    lernparadies.vokali.flexionsart:
        class: Lernparadies\VokaliBundle\Admin\FlexionsartAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Vokali"
              label: "Flexionsarten"
        arguments:
            - ~
            - Lernparadies\VokaliBundle\Entity\Flexionsart
            - ~
    lernparadies.vokali.wortart:
        class: Lernparadies\VokaliBundle\Admin\WortartAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Vokali"
              label: "Wortarten"
        arguments:
            - ~
            - Lernparadies\VokaliBundle\Entity\Wortart
            - ~