<?php

namespace Lernparadies\VokaliBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FlexionsartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlexionsartRepository extends EntityRepository
{
}
