<?php

namespace Lernparadies\VokaliBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Lernparadies\VokaliBundle\Entity\WortWortartXFlexion;;

/**
 * Wort_WortartXFlexionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WortWortartXFlexionRepository extends EntityRepository
{
    /**
     * @var \Lernparadies\VokaliBundle\Entity\WortWortartXFlexion
     */
    protected $wortWortartXFlexion;

    /**
     *
     */
    public function createNew(){
        $this->wortWortartXFlexion = new WortWortartXFlexion();
    }

    /**
     * @param $wort
     */
    public function setWort($wort){
          $this->wortWortartXFlexion->setWort($this->getEntityManager()->getRepository('LernparadiesVokaliBundle:Wort')->findAndSaveIfNew($wort));
    }

    /**
     * @param $flexionsart
     */
    public function setFlexionsart($flexionsart){
        $this->wortWortartXFlexion->setFlexionsart($flexionsart);
    }

    /**
     * @param $flexionsart
     */
    public function setWortXWortart($wortxwortart){
        $this->wortWortartXFlexion->setWortxwortart($wortxwortart);
    }

    /**
     *
     */
    public function save(){
        $this->getEntityManager()->persist($this->wortWortartXFlexion);
        return $this->getFlexion();
    }

    public function getFlexion()
    {
        return $this->wortWortartXFlexion;
    }
}
