<?php

namespace Lernparadies\VokaliBundle\Entity;

use Doctrine\Common\Proxy\Exception\InvalidArgumentException;
use Doctrine\ORM\EntityRepository;
use Lernparadies\LernparadiesBundle\Entity\Sprache;
use Lernparadies\VokaliBundle\Entity\Wort;
use Lernparadies\VokaliBundle\Entity\Wortart;
use Lernparadies\VokaliBundle\Entity\Flexionsart;

/**
 * WortXWortartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WortXWortartRepository extends EntityRepository
{
    /**
     * @var \Lernparadies\VokaliBundle\Entity\WortXWortart
     */
    protected $wortXWortart;

    public function getWortXWortart(){
        return $this->wortXWortart;
    }

    public function createWort( $wort = null, $wortart = null, $sprache = null ){
        $this->wortXWortart = new WortXWortart();
        $this->setWort($wort);
        $this->setWortart($wortart);
        $this->setSprache($sprache);
    }

    /**
     * @param $wort
     */
    public function setWort( $wort ){
        $this->wortXWortart->setWort($this->doctrine->getRepository('LernparadiesVokaliBundle:Wort')->findAndSaveIfNew($wort));
    }

    /**
     * @param $wortart
     */
    public function setWortart( $wortart ){
        $this->wortXWortart->setWortart($this->doctrine->getRepository('LernparadiesVokaliBundle:Wortart')->findWortart($wortart));
    }

    /**
     * @param $sprache
     */
    public function setSprache( $sprache ){
        $this->wortXWortart->setSprache($this->doctrine->getRepository('LernparadiesVokaliBundle:Wortart')->findSprache($sprache));
    }

    /**
     * @param $wort
     * @param Flexionsart $flexionsart
     */
    public function setFlexion( $wort, Flexionsart $flexionsart ){
        $this->save();
        $this->doctrine->getRepository('LernparadiesVokaliBundle:Flexionsart')->createNew();
        $this->doctrine->getRepository('LernparadiesVokaliBundle:Flexionsart')->setWortXWortart($this->wortXWortart);
        $this->doctrine->getRepository('LernparadiesVokaliBundle:Flexionsart')->setWort($wort);
        $this->doctrine->getRepository('LernparadiesVokaliBundle:Flexionsart')->setFlexionsart($flexionsart);
        $this->doctrine->getRepository('LernparadiesVokaliBundle:Flexionsart')->save();
    }
    public function save(){
        $this->getEntityManager()->persist($this->wortXWortart);
    }
}
