<?php

namespace Lernparadies\VokaliBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Lernparadies\VokaliBundle\Exception\WortException;

/**
 * WortRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WortRepository extends EntityRepository
{
    private $co = 0;
    /**
     * @param $wort2SearchFor
     * @return Wort|object
     * @throws WortException
     */
    public function findAndSaveIfNew( $wort2SearchFor ){
        $this->co++;
        if(is_string($wort2SearchFor)){
            $wort = $this->getEntityManager()->getRepository('LernparadiesVokaliBundle:Wort')->findOneBy( array( 'wortName' => $wort2SearchFor ) );

            if(!$wort)
            {
                $wort = new Wort();
                $wort->setWortName($wort2SearchFor);
                $this->getEntityManager()->persist($wort);
                $this->getEntityManager()->flush();
            }
            return $wort;
        }elseif(is_object($wort2SearchFor) && get_class($wort2SearchFor) == 'Lernparadies\VokaliBundle\Entity\Wort'){
            return $wort2SearchFor;
        };
        throw new WortException();
        //notFoundNeitherSaved($wort2SearchFor);
    }
}
