<?php

namespace Lernparadies\VokaliBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Wort_WortartXFlexionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Wort_WortartXFlexionRepository extends EntityRepository
{
    /**
     * @var \Lernparadies\VokaliBundle\Entity\Wort_WortartXFlexion
     */
    protected $wortWortartXFlexion;

    /**
     *
     */
    public function createNew(){
        $this->wortWortartXFlexion = new Wort_WortartXFlexion();
    }

    /**
     * @param $wortXWortart
     */
    public function setWortXWortart($wortXWortart){
        $this->wortWortartXFlexion->setWortxwortart($wortXWortart);
    }

    /**
     * @param $wort
     */
    public function setWort($wort){
          $this->wortWortartXFlexion->setWort($this->doctrine->getRepository('LernparadiesVokaliBundle:Wort')->findAndSaveIfNew($wort));
    }

    /**
     * @param $flexionsart
     */
    public function setFlexionsart($flexionsart){
        $this->wortWortartXFlexion->setFlexionsart($flexionsart);
    }

    /**
     *
     */
    public function save(){
        $this->getEntityManager()->persist($this->wortWortartXFlexion);
    }
}
