<?php

namespace Lernparadies\VokaliBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WortartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WortartRepository extends EntityRepository
{
    /**
     * @param $wortart2SearchFor
     * @return bool|object
     */
    public function findWortart( $wortart2SearchFor ){
        if(is_string($wortart2SearchFor)){
            $wortart = $this->doctrine->getRepository('LernparadiesVokaliBundle:Wortart')->findOneBy( array( 'wortartName' => $wortart2SearchFor ) );
            return $wortart;
        }elseif(is_object($wortart2SearchFor) && get_class($wortart2SearchFor) == 'Lernparadies\VokaliBundle\Entity\Wortart'){
            return $wortart2SearchFor;
        }
        return false;
    }
}
