Lernparadies\VokaliBundle\Entity\WortWortartXFlexion:
    type: entity
    table: WORT_WORTART_X_FLEXION
    repositoryClass: Lernparadies\VokaliBundle\Entity\WortWortartXFlexionRepository
    fields:
        id:
            id: true
            type: integer
            unsigned: true
            nullable: false
            column: ID
            generator:
                strategy: IDENTITY
        created_at:
            type: datetime
            nullable: false
            column: NEWDATE
        updated_at:
            type: datetime
            nullable: false
            column: EDITDATE
    manyToOne:
        wort:
            targetEntity: Wort
            cascade: ["persist"]
            mappedBy: null
            inversedBy: null
            nullable: false
            name: wort
            joinColumns:
                WORT:
                    referencedColumnName: WORT_ID
            orphanRemoval: false
        wortxwortart:
            targetEntity: WortXWortart
            cascade: {  }
            inversedBy: flexionen
            nullable: false
            name: wortxwortart
            joinColumns:
                WORT_X_WORTART:
                    referencedColumnName: ID
            orphanRemoval: false
        flexionsart:
            targetEntity: Flexionsart
            cascade: {  }
            mappedBy: null
            inversedBy: null
            nullable: false
            name: flexionsart
            joinColumns:
                FLEXIONSART:
                    referencedColumnName: FLEXIONSART_ID
            orphanRemoval: false
    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue ]
        preUpdate: [ setUpdatedAtValue ]
