Lernparadies\LernparadiesBenutzerBundle\Entity\Benutzer:
    type: entity
    table: BENUTZER
    fields:
        id:
            id: true
            type: integer
            unsigned: true
            nullable: false
            column: BENUTZER_ID
            generator:
                strategy: IDENTITY
        benutzerNewdate:
            type: datetime
            nullable: false
            column: BENUTZER_NEWDATE
        benutzerEditdate:
            type: datetime
            nullable: false
            column: BENUTZER_EDITDATE
        benutzerFriendlyUrl:
            type: string
            length: 64
            fixed: false
            nullable: false
            unique: true
            column: BENUTZER_FRIENDLY_URL
    manyToMany:
        groups:
            targetEntity: Benutzergruppe
            joinTable:
                name: BENUTZER_XX_BENUTZERGRUPPE
                joinColumns:
                    user_id:
                        referencedColumnName: BENUTZER_ID
                inverseJoinColumns:
                    group_id:
                        referencedColumnName: BENUTZERGRUPPE_ID
    lifecycleCallbacks:
        prePersist: [ setBenutzerNewdate, setDefaultParameterAtCreation ]
        preUpdate: [ setBenutzerEditdate ]