wortart:
    pattern:  /
    defaults: { _controller: "LernparadiesVokaliBundle:Wortart:index" }

wortart_show:
    pattern:  /{id}/show
    defaults: { _controller: "LernparadiesVokaliBundle:Wortart:show" }

wortart_new:
    pattern:  /new
    defaults: { _controller: "LernparadiesVokaliBundle:Wortart:new" }

wortart_create:
    pattern:  /create
    defaults: { _controller: "LernparadiesVokaliBundle:Wortart:create" }
    requirements: { _method: post }

wortart_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "LernparadiesVokaliBundle:Wortart:edit" }

wortart_update:
    pattern:  /{id}/update
    defaults: { _controller: "LernparadiesVokaliBundle:Wortart:update" }
    requirements: { _method: post|put }

wortart_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "LernparadiesVokaliBundle:Wortart:delete" }
    requirements: { _method: post|delete }
