<?php

namespace Lernparadies\LernparadiesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SpracheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpracheRepository extends EntityRepository
{
    /**
     * @param $sprache2SearchFor
     * @return bool|object
     */
    public function findSprache( $sprache2SearchFor ){
        if(is_string($sprache2SearchFor)){
            $sprache = $this->doctrine->getRepository('LernparadiesLernparadiesBundle:Sprache')->findOneBy( array( 'spracheCode' => $sprache2SearchFor ) );
            return $sprache;
        }elseif(is_object($sprache2SearchFor) && get_class($sprache2SearchFor) == 'Lernparadies\LernparadiesBundle\Entity\Sprache'){
            return $sprache2SearchFor;
        }
        return false;
    }
}
