services:
    x.blog.admin.post:
        class: Lernparadies\LernparadiesBlogBundle\Admin\PostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: tutorial_blog, label: post }
        arguments: [null, Lernparadies\LernparadiesBlogBundle\Entity\Post, LernparadiesBlogBundle:PostAdmin]
   x.blog.admin.tag:
        class: Lernparadies\LernparadiesBlogBundle\Admin\TagAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: tutorial_blog, label: tag }
        arguments: [null, Lernparadies\LernparadiesBlogBundle\Entity\Tag, LernparadiesBlogBundle:TagAdmin]
   x.blog.admin.comment:
        class: Lernparadies\LernparadiesBlogBundle\Admin\KommentarAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: tutorial_blog, label: comment }
        arguments: [null, Lernparadies\LernparadiesBlogBundle\Entity\Kommentar, LernparadiesBlogBundle:KommentarAdmin]