parameters:
#    lernparadies_lernparadies_blog.example.class: Lernparadies\LernparadiesBlogBundle\Example

services:
   tutorial.blog.admin.post:
      class: Lernparadies\LernparadiesBlogBundle\Admin\PostAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: tutorial_blog, label: post }
      arguments: [null, Lernparadies\LernparadiesBlogBundle\Entity\Post, LernparadiesBlogBundle:PostAdmin]