parameters:
#    lernparadies_lernparadies_blog.example.class: Lernparadies\LernparadiesBlogBundle\Example

services:
#    lernparadies_lernparadies_blog.example:
#        class: %lernparadies_lernparadies_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
