Lernparadies\LernparadiesBlogBundle\Entity\Comment:
    type: entity
    table: KOMMENTAR
    fields:
        id:
            id: true
            type: integer
            unsigned: true
            nullable: false
            column: KOMMENTAR_ID
            generator:
                strategy: IDENTITY
        created_at:
            type: datetime
            nullable: false
            column: KOMMENTAR_NEWDATE
        updated_at:
            type: datetime
            nullable: false
            column: KOMMENTAR_EDITDATE
        name:
            type: string
            nullable: false
            column: KOMMENTAR_NAME
        email:
            type: string
            column: KOMMENTAR_EMAIL
        url:
            type: string
            column: KOMMENTAR_URL
        message:
            type: text
            column: KOMMENTAR_MESSAGE
    manyToOne:
        post:
            targetEntity: Post
            mappedBy: Post
    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue ]
        preUpdate: [ setUpdatedAtValue ]